# Generated by Django 4.2.5 on 2023-09-21 11:46

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название линий')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Ссылка')),
                ('number', models.CharField(blank=True, max_length=3, verbose_name='Номер линий')),
                ('color', colorfield.fields.ColorField(default='#EF161E', image_field=None, max_length=25, samples=None, verbose_name='Цвет линий')),
            ],
        ),
    ]
