# Generated by Django 4.2.5 on 2023-09-27 14:16

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название города')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название линий')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Ссылка')),
                ('number', models.CharField(blank=True, max_length=3, verbose_name='Номер линий')),
                ('color', colorfield.fields.ColorField(default='#EF161E', image_field=None, max_length=25, samples=None, verbose_name='Цвет линий')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.city')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, default='images/plugs/plug_line.jpg', upload_to='images/%Y/%M/%D', verbose_name='Картинка')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.line', verbose_name='линия')),
            ],
        ),
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, default='images/plugs/plug_city.jpg', upload_to='images/%Y/%M/%D', verbose_name='Картинка')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.city', verbose_name='линия')),
            ],
        ),
    ]
