# Generated by Django 4.2.5 on 2023-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityinfo',
            options={'verbose_name': 'Информация о городе', 'verbose_name_plural': 'Информация о городе'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Линия', 'verbose_name_plural': 'Линии'},
        ),
        migrations.AlterModelOptions(
            name='lineinfo',
            options={'verbose_name': 'Информация о линий', 'verbose_name_plural': 'Информация о линий'},
        ),
        migrations.AlterField(
            model_name='cityinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%M/%D', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='lineinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%M/%D', verbose_name='Картинка'),
        ),
    ]
