# Generated by Django 4.2.5 on 2023-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0002_alter_cityinfo_options_alter_line_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineinfo',
            name='line',
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%M/%D', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='city',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='line',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%M/%D', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='line',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.DeleteModel(
            name='CityInfo',
        ),
        migrations.DeleteModel(
            name='LineInfo',
        ),
    ]
