# Generated by Django 4.2.5 on 2023-10-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0004_remove_city_info_remove_line_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='line',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
