# Generated by Django 4.2.5 on 2023-10-22 05:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0005_city_content_line_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='color_text',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название метрополитена'),
        ),
        migrations.AlterField(
            model_name='line',
            name='color',
            field=colorfield.fields.ColorField(default='#EF161E', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
    ]
