# Generated by Django 4.2.5 on 2023-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0007_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('Эксплуатируйся', '🚇 Эксплуатируйся'), ('Строящиеся', '🛠️ Строящиеся'), ('Проектируемая', '📄 Проектируемая'), ('Закрытая', '🔒 Закрытая')], max_length=200),
        ),
    ]
