# Generated by Django 4.2.5 on 2023-10-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0008_alter_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.line', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('Эксплуатируется', '🚇 Эксплуатируется'), ('Строящиеся', '🛠️ Строящиеся'), ('Проектируемая', '📄 Проектируемая'), ('Закрытая', '🔒 Закрытая')], default='Эксплуатируется', max_length=200, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='station',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название станций'),
        ),
    ]
