# Generated by Django 4.2.5 on 2023-10-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0009_alter_line_city_alter_station_line_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['num_of_station', 'title'], 'verbose_name': 'Станция', 'verbose_name_plural': 'Станций'},
        ),
        migrations.AddField(
            model_name='station',
            name='num_of_station',
            field=models.IntegerField(default=1, verbose_name='Номер линий (север-юг/восток-запад)'),
        ),
    ]
