# Generated by Django 4.2.5 on 2023-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0010_alter_station_options_station_num_of_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('Эксплуатируется', '🚇 Эксплуатируется'), ('Строится', '🛠️ Строится'), ('Проектируется', '✏ Проектируется'), ('Планируется', '📄 Планируется'), ('Закрыта', '🔒 Закрыта')], default='Эксплуатируется', max_length=200, verbose_name='Статус'),
        ),
    ]
