# Generated by Django 4.2.5 on 2023-10-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0011_alter_station_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.line', verbose_name='Линия')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='transfers',
            field=models.ManyToManyField(blank=True, to='metro_wiki.linetransfers', verbose_name='Пересадки'),
        ),
    ]
