# Generated by Django 4.2.5 on 2023-10-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0012_linetransfers_station_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.line', verbose_name='Линия')),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='transfers',
        ),
        migrations.DeleteModel(
            name='LineTransfers',
        ),
        migrations.AddField(
            model_name='transfers',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.station', verbose_name='Станций'),
        ),
    ]
