# Generated by Django 4.2.5 on 2023-10-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0013_transfers_remove_station_transfers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name': 'Пересадка', 'verbose_name_plural': 'Пересадки'},
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='station',
            new_name='stations',
        ),
        migrations.AddField(
            model_name='station',
            name='transfer',
            field=models.ManyToManyField(blank=True, related_name='+', to='metro_wiki.transfers', verbose_name='Пересадки'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='station',
            name='num_of_station',
            field=models.IntegerField(default=1, verbose_name='Номер станций (север-юг/восток-запад)'),
        ),
    ]
