# Generated by Django 4.2.5 on 2023-10-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0014_alter_transfers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='title',
        ),
    ]
