# Generated by Django 4.2.5 on 2023-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0015_remove_transfers_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
