# Generated by Django 4.2.5 on 2023-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0017_alter_station_transfer_delete_transfers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['title'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='station',
            name='next_path',
            field=models.CharField(choices=[('Эксплуатируется', '🚇 Эксплуатируется'), ('Строится', '🛠️ Строится'), ('Ничего', 'Ничего')], default='Эксплуатируется', max_length=200, verbose_name='Путь к следующей станций'),
        ),
        migrations.AddField(
            model_name='station',
            name='prev_path',
            field=models.CharField(choices=[('Эксплуатируется', '🚇 Эксплуатируется'), ('Строится', '🛠️ Строится'), ('Ничего', 'Ничего')], default='Эксплуатируется', max_length=200, verbose_name='Путь к предыдущей станций'),
        ),
    ]
