# Generated by Django 4.2.5 on 2023-10-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0018_alter_city_options_station_next_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='prev_direction',
            field=models.CharField(choices=[('Основной путь', 'Основной путь'), ('Ответвление', 'Ответвление'), ('Начало ответвления', 'Начало ответвления'), ('Конец ответвления', 'Конец ответвления')], default='Основной путь', max_length=200, verbose_name='Тип пути'),
        ),
    ]
