# Generated by Django 4.2.5 on 2023-10-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0019_station_prev_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='prev_direction',
            new_name='path_direction',
        ),
    ]
