# Generated by Django 4.2.5 on 2023-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0020_rename_prev_direction_station_path_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['number', 'title'], 'verbose_name': 'Линия', 'verbose_name_plural': 'Линии'},
        ),
    ]
