# Generated by Django 4.2.5 on 2023-10-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0021_alter_line_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['index', 'title'], 'verbose_name': 'Станция', 'verbose_name_plural': 'Станций'},
        ),
        migrations.RenameField(
            model_name='station',
            old_name='num_of_station',
            new_name='index',
        ),
    ]
