# Generated by Django 4.2.5 on 2023-10-28 12:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0022_alter_station_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='line',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='station',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
