# Generated by Django 4.2.5 on 2023-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0025_depot_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='number_of_depot',
            field=models.IntegerField(default=1, verbose_name='Номер депо'),
        ),
    ]
