# Generated by Django 4.2.5 on 2023-11-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0026_depot_number_of_depot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depot',
            options={'ordering': ['city', 'number_of_depot'], 'verbose_name': 'Депо', 'verbose_name_plural': 'Депо'},
        ),
        migrations.AddField(
            model_name='depot',
            name='main_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.line', verbose_name='Линия на котором она расположена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depot',
            name='status',
            field=models.CharField(choices=[('Эксплуатируется', '🚇 Эксплуатируется'), ('Строится', '🛠️ Строится'), ('Проектируется', '✏ Проектируется'), ('Планируется', '📄 Планируется'), ('Закрыта', '🔒 Закрыта')], default='Эксплуатируется', max_length=200, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название депо'),
        ),
    ]
