# Generated by Django 4.2.5 on 2023-11-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0027_alter_depot_options_depot_main_line_depot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='+', to='metro_wiki.line', verbose_name='Другие обслуживаемые линии'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='main_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metro_wiki.line', verbose_name='Линия на котором она расположена'),
        ),
    ]
