# Generated by Django 4.2.5 on 2023-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0028_alter_depot_lines_alter_depot_main_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, help_text='Оставьте поле  пустым, чтобы сгенерировать автоматически', max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='slug',
            field=models.CharField(blank=True, help_text='Оставьте поле  пустым, чтобы сгенерировать автоматически', max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='line',
            name='slug',
            field=models.CharField(blank=True, help_text='Оставьте поле  пустым, чтобы сгенерировать автоматически', max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.CharField(blank=True, help_text='Оставьте поле  пустым, чтобы сгенерировать автоматически', max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='train',
            name='slug',
            field=models.CharField(blank=True, help_text='Оставьте поле  пустым, чтобы сгенерировать автоматически', max_length=100, unique=True, verbose_name='Ссылка'),
        ),
    ]
