# Generated by Django 4.2.5 on 2023-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0029_alter_city_slug_alter_depot_slug_alter_line_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['line', 'index', 'title'], 'verbose_name': 'Станция', 'verbose_name_plural': 'Станций'},
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='line',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='station',
            name='transfer',
            field=models.ManyToManyField(blank=True, help_text='После добавления пересадок, вам нужно ещё раз сохранить станцию', related_name='+', to='metro_wiki.station', verbose_name='Пересадки'),
        ),
        migrations.AlterField(
            model_name='train',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Ссылка'),
        ),
    ]
