# Generated by Django 4.2.5 on 2023-09-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='Ссылка')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='images/%Y/%M/%D', verbose_name='Картинка')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-time_created'],
            },
        ),
    ]
