# Generated by Django 4.2.5 on 2023-09-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metro_wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.CharField(max_length=250, unique=True, verbose_name='Ссылка')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, default='images/plugs/plug_news.jpg', upload_to='images/%Y/%M/%D', verbose_name='Картинка')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.line', verbose_name='линия')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-time_created'],
            },
        ),
    ]
