# Generated by Django 4.2.5 on 2023-10-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_blog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Источник'),
        ),
    ]
