# Generated by Django 4.2.5 on 2023-09-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_line_options'),
        ('metro_blog', '0003_blog_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.line', verbose_name='линия'),
        ),
    ]
