# Generated by Django 4.2.5 on 2023-11-10 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0028_alter_depot_lines_alter_depot_main_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metro_blog', '0005_alter_blog_content_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metro_wiki.city', verbose_name='Город'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='line',
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='blog',
            name='line',
            field=models.ManyToManyField(blank=True, null=True, to='metro_wiki.line', verbose_name='линий'),
        ),
    ]
