# Generated by Django 4.2.5 on 2023-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_wiki', '0028_alter_depot_lines_alter_depot_main_line'),
        ('metro_blog', '0006_blog_city_remove_blog_line_alter_blog_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='line',
            field=models.ManyToManyField(blank=True, to='metro_wiki.line', verbose_name='линий'),
        ),
    ]
