# Generated by Django 4.2.5 on 2023-11-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_blog', '0007_alter_blog_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный'),
        ),
    ]
