# Generated by Django 4.2.5 on 2023-11-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro_blog', '0008_alter_blog_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
